import {
    AddOutlined as AddOutlinedIcon,
    ExpandMore as ExpandMoreIcon,
    NavigateBefore as NavigateBeforeIcon,
    NavigateNext as NavigateNextIcon,
    EditOutlined as EditOutlinedIcon,
    PeopleAltOutlined as PeopleAltOutlinedIcon,
    AccessTimeOutlined as AccessTimeOutlinedIcon,
    CalendarTodayOutlined as CalendarTodayOutlinedIcon,
    KeyboardArrowDownOutlined as KeyboardArrowDownOutlinedIcon,
    VideoCameraFront as VideoCameraFrontIcon,
    Phone as PhoneIcon,
    Room as RoomIcon,
    FormatBold as FormatBoldIcon,
    FormatItalic as FormatItalicIcon,
    FormatUnderlined as FormatUnderlinedIcon,
    FormatListBulleted as FormatListBulletedIcon,
    FormatListNumbered as FormatListNumberedIcon,
    InsertLink as InsertLinkIcon,
    Undo as UndoIcon,
    Redo as RedoIcon,
    ContentCopyOutlined as ContentCopyOutlinedIcon,
    Close as CloseIcon,
    ArrowForwardIos as ArrowForwardIosIcon,
    ChevronLeftOutlined as ChevronLeftOutlinedIcon,
    PublicOutlined as PublicOutlinedIcon,
    AddCircleOutline as AddCircleOutlineIcon,
    SettingsOutlined as SettingsOutlinedIcon,
    ArrowDropDown as ArrowDropDownIcon,
    FilterListOutlined as FilterListOutlinedIcon,
    AutorenewOutlined as AutorenewOutlinedIcon,
    OutlinedFlagOutlined as OutlinedFlagOutlinedIcon,
    KeyboardArrowDown as KeyboardArrowDownIcon,
    SystemUpdateAlt as SystemUpdateAltIcon,
    FilterList as FilterListIcon,
    CalendarMonth as CalendarMonthIcon,
    ViewList as ViewListIcon,
    ContentCopy as ContentCopyIcon,
    ArrowBackIos as ArrowBackIosIcon,
    FmdGoodOutlined as FmdGoodOutlinedIcon,
    LocalPhoneOutlined as LocalPhoneOutlinedIcon,
    AccessTime as AccessTimeIcon,
    VideocamOutlined as VideocamOutlinedIcon,
    BuildOutlined as BuildOutlinedIcon,
    ArrowBackOutlined as ArrowBackOutlinedIcon,
    LinkOutlined as LinkOutlinedIcon,
   IosShareOutlined as IosShareOutlinedIcon,
   Menu as MenuIcon,
   ArrowForwardIosOutlined as ArrowForwardIosOutlinedIcon,
   EventNote as EventNoteIcon,
   EmailOutlined as EmailOutlinedIcon,
   Circle as CircleIcon,
   ErrorOutlineOutlined as ErrorOutlineOutlinedIcon,
   ExpandLessOutlined as ExpandLessOutlinedIcon,
   DoNotDisturbOnOutlined as DoNotDisturbOnOutlinedIcon,
   ExpandCircleDownOutlined as ExpandCircleDownOutlinedIcon,
   PestControlOutlined as PestControlOutlinedIcon,
   RemoveRedEyeOutlined as RemoveRedEyeOutlinedIcon,
   MoreHorizOutlined as MoreHorizOutlinedIcon,
   ArrowForward as ArrowForwardIcon,
   KeyboardDoubleArrowRightRounded as KeyboardDoubleArrowRightRoundedIcon,
   AccountCircleOutlined as AccountCircleOutlinedIcon,
   AttachFileOutlined as AttachFileOutlinedIcon,
   TodayOutlined as TodayOutlinedIcon,
   TranslateSharp as TranslateSharpIcon,
   MailOutlineSharp as MailOutlineSharpIcon,
   ArrowUpwardSharp as ArrowUpwardSharpIcon,
   ThumbUpAltOutlined as ThumbUpAltOutlinedIcon,
   FolderOutlined as FolderOutlinedIcon,
   CheckCircleOutlineOutlined as CheckCircleOutlineOutlinedIcon,
   SellOutlined as SellOutlinedIcon,
   WorkspacesOutlined as WorkspacesOutlinedIcon,
   FormatBoldOutlined as FormatBoldOutlinedIcon,
   FormatItalicOutlined as FormatItalicOutlinedIcon,
   FormatUnderlinedOutlined as FormatUnderlinedOutlinedIcon,
   StrikethroughSOutlined as StrikethroughSOutlinedIcon,
   CodeOffOutlined as CodeOffOutlinedIcon,
   FormatListNumberedOutlined as FormatListNumberedOutlinedIcon,
   FormatListBulletedOutlined as FormatListBulletedOutlinedIcon,
   InsertLinkOutlined as InsertLinkOutlinedIcon,
   PhotoSizeSelectActual as PhotoSizeSelectActualIcon,
   Tag as TagIcon,
   AttachFile as AttachFileIcon,
   RadioButtonChecked as RadioButtonCheckedIcon,
   FormatColorText as FormatColorTextIcon,
   AutoFixHigh as AutoFixHighIcon,
   CloseOutlined as CloseOutlinedIcon,
  MoreVertOutlined as MoreVertOutlinedIcon,
  ChatBubbleOutlineOutlined as ChatBubbleOutlineOutlinedIcon,
  LockOutlined as LockOutlinedIcon,
  SearchOutlined as SearchOutlinedIcon,
  Straight as StraightIcon,
  LocalOfferOutlined as LocalOfferOutlinedIcon,
  TranslateOutlined as TranslateOutlinedIcon,
  SentimentSatisfiedAlt as SentimentSatisfiedAltIcon,
  SentimentSatisfied as SentimentSatisfiedIcon,
  SentimentVeryDissatisfied as SentimentVeryDissatisfiedIcon,
  Person as PersonIcon,
  BusinessOutlined as BusinessOutlinedIcon,
  ArrowForwardIosSharp as ArrowForwardIosSharpIcon,
  DragIndicator as DragIndicatorIcon,
  Add as AddIcon,
  DeleteOutline as DeleteOutlineIcon,
  RedoOutlined as RedoOutlinedIcon,
  Campaign as CampaignIcon,
  ReplayOutlined as ReplayOutlinedIcon,
  RefreshOutlined as RefreshOutlinedIcon,
  ReportGmailerrorred as ReportGmailerrorredIcon,
  Edit as EditIcon,
  ArrowBack as ArrowBackIcon,
  ArrowDropUp as ArrowDropUpIcon,
  InfoOutlined as InfoOutlinedIcon,
  CheckCircle as CheckCircleIcon,
  OpenInNew as OpenInNewIcon,
  PermIdentityOutlined as PermIdentityOutlinedIcon,


   } from "@mui/icons-material";
  
  // Export all icons
  export {
    AddOutlinedIcon,
    ExpandMoreIcon,
    NavigateBeforeIcon,
    NavigateNextIcon,
    EditOutlinedIcon,
    PeopleAltOutlinedIcon,
    AccessTimeOutlinedIcon,
    CalendarTodayOutlinedIcon,
    KeyboardArrowDownOutlinedIcon,
    VideoCameraFrontIcon,
    PhoneIcon,
    RoomIcon,
    FormatBoldIcon,
    FormatItalicIcon,
    FormatUnderlinedIcon,
    FormatListBulletedIcon,
    FormatListNumberedIcon,
    InsertLinkIcon,
    UndoIcon,
    RedoIcon,
    ContentCopyOutlinedIcon,
    CloseIcon,
    ArrowForwardIosIcon,
    ChevronLeftOutlinedIcon,
    PublicOutlinedIcon,
    AddCircleOutlineIcon,
    SettingsOutlinedIcon,
    ArrowDropDownIcon,
    FilterListOutlinedIcon,
    AutorenewOutlinedIcon,
    OutlinedFlagOutlinedIcon,
    KeyboardArrowDownIcon,
    SystemUpdateAltIcon,
    FilterListIcon,
    CalendarMonthIcon,
    ViewListIcon,
    ContentCopyIcon,
    ArrowBackIosIcon,
    FmdGoodOutlinedIcon,
    LocalPhoneOutlinedIcon,
    AccessTimeIcon,
    VideocamOutlinedIcon,
    BuildOutlinedIcon,
    ArrowBackOutlinedIcon,
    LinkOutlinedIcon,
    IosShareOutlinedIcon,
    MenuIcon,
    ArrowForwardIosOutlinedIcon,
    EventNoteIcon,
    EmailOutlinedIcon,
    CircleIcon,
    ErrorOutlineOutlinedIcon,
    ExpandLessOutlinedIcon,
    DoNotDisturbOnOutlinedIcon,
    ExpandCircleDownOutlinedIcon,
    PestControlOutlinedIcon,
    RemoveRedEyeOutlinedIcon,
    MoreHorizOutlinedIcon,
    ArrowForwardIcon,
    KeyboardDoubleArrowRightRoundedIcon,
    AccountCircleOutlinedIcon,
    AttachFileOutlinedIcon,
    TodayOutlinedIcon,
    TranslateSharpIcon,
    MailOutlineSharpIcon,
    ArrowUpwardSharpIcon,
    ThumbUpAltOutlinedIcon,
    FolderOutlinedIcon,
    CheckCircleOutlineOutlinedIcon,
    SellOutlinedIcon,
    WorkspacesOutlinedIcon,
    FormatBoldOutlinedIcon,
    FormatItalicOutlinedIcon,
    FormatUnderlinedOutlinedIcon,
    StrikethroughSOutlinedIcon,
    CodeOffOutlinedIcon,
    FormatListNumberedOutlinedIcon,
    FormatListBulletedOutlinedIcon,
    InsertLinkOutlinedIcon,
    PhotoSizeSelectActualIcon,
    TagIcon,
    AttachFileIcon,
    RadioButtonCheckedIcon,
   FormatColorTextIcon,
   AutoFixHighIcon,
   CloseOutlinedIcon,
   MoreVertOutlinedIcon,
   ChatBubbleOutlineOutlinedIcon,
   LockOutlinedIcon,
   SearchOutlinedIcon,
   StraightIcon,
   LocalOfferOutlinedIcon,
   TranslateOutlinedIcon,
   SentimentSatisfiedAltIcon,
   SentimentSatisfiedIcon,
   SentimentVeryDissatisfiedIcon,
   PersonIcon,
   BusinessOutlinedIcon,
   ArrowForwardIosSharpIcon,
   DragIndicatorIcon,
   AddIcon,
   DeleteOutlineIcon,
   RedoOutlinedIcon,
   CampaignIcon,
   ReplayOutlinedIcon,
   RefreshOutlinedIcon,
   ReportGmailerrorredIcon,
   EditIcon,
   ArrowBackIcon,
   ArrowDropUpIcon,
   InfoOutlinedIcon,
   CheckCircleIcon,
   OpenInNewIcon,
   PermIdentityOutlinedIcon,
  
};